export interface ApiResponse<T = any> {
  success: boolean;
  data?: T;
  error?: {
    code: string;
    message: string;
  };
  timestamp: number;
}

export interface ApiError {
  code: string;
  message: string;
  details?: any;
}

export interface PaginationResponse<T> {
  items: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
  hasNext: boolean;
  hasPrev: boolean;
}

// 标准错误代码
export const ERROR_CODES = {
  // 身份验证相关
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_TOKEN: "INVALID_TOKEN",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  
  // 用户身份相关
  IDENTITY_REQUIRED: "IDENTITY_REQUIRED",
  IDENTITY_NOT_FOUND: "IDENTITY_NOT_FOUND",
  IDENTITY_ALREADY_EXISTS: "IDENTITY_ALREADY_EXISTS",
  
  // 匹配相关
  MATCH_TIMEOUT: "MATCH_TIMEOUT",
  MATCH_CANCELLED: "MATCH_CANCELLED",
  MATCH_ALREADY_EXISTS: "MATCH_ALREADY_EXISTS",
  MATCH_NOT_FOUND: "MATCH_NOT_FOUND",
  MATCH_ALREADY_RESOLVED: "MATCH_ALREADY_RESOLVED",
  
  // 房间相关
  ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  ROOM_CLOSED: "ROOM_CLOSED",
  ROOM_PAUSED: "ROOM_PAUSED",
  ROOM_FULL: "ROOM_FULL",
  NOT_PARTICIPANT: "NOT_PARTICIPANT",
  NOT_DIRECTOR: "NOT_DIRECTOR",
  NOT_YOUR_TURN: "NOT_YOUR_TURN",
  
  // 火花标记相关
  ALREADY_SPARKED: "ALREADY_SPARKED",
  MESSAGE_NOT_FOUND: "MESSAGE_NOT_FOUND",
  
  // 投票相关
  VOTE_IN_PROGRESS: "VOTE_IN_PROGRESS",
  VOTE_NOT_FOUND: "VOTE_NOT_FOUND",
  VOTE_CLOSED: "VOTE_CLOSED",
  ALREADY_VOTED: "ALREADY_VOTED",
  
  // 脑洞相关
  BRAINHOLE_NOT_FOUND: "BRAINHOLE_NOT_FOUND",
  BRAINHOLE_ALREADY_COLLECTED: "BRAINHOLE_ALREADY_COLLECTED",
  BRAINHOLE_NOT_COLLECTED: "BRAINHOLE_NOT_COLLECTED",
  
  // 反应相关
  REACTION_NOT_FOUND: "REACTION_NOT_FOUND",
  REACTION_LIMIT_EXCEEDED: "REACTION_LIMIT_EXCEEDED",
  
  // 限流相关
  RATE_LIMITED: "RATE_LIMITED",
  
  // 验证相关
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_INPUT: "INVALID_INPUT",
  
  // 数据库相关
  DATABASE_ERROR: "DATABASE_ERROR",
  RECORD_NOT_FOUND: "RECORD_NOT_FOUND",
  UNIQUE_CONSTRAINT_VIOLATION: "UNIQUE_CONSTRAINT_VIOLATION",
  
  // 服务器相关
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  
  // AI相关
  AI_SERVICE_UNAVAILABLE: "AI_SERVICE_UNAVAILABLE",
  AI_GENERATION_FAILED: "AI_GENERATION_FAILED",
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];